dotter: fixed escaping in some file

diff --git a/gh-dash/config.yml b/gh-dash/config.yml
--- a/gh-dash/config.yml
+++ b/gh-dash/config.yml
@@ -68,19 +68,19 @@ keybindings:
     name: Clone and checkout
     command: >
       if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
-        echo "Already inside a Git repository. Attempting to checkout branch: {{.HeadRefName}}" &&
-        if ! git checkout "{{.HeadRefName}}"; then
-          echo "Failed to checkout branch: {{.HeadRefName}}" && exit 1;
+        echo "Already inside a Git repository. Attempting to checkout branch: \{{.HeadRefName}}" &&
+        if ! git checkout "\{{.HeadRefName}}"; then
+          echo "Failed to checkout branch: \{{.HeadRefName}}" && exit 1;
         fi &&
         exit 0;
       fi &&
-      if [ -d "$(basename {{.RepoName}})" ]; then
-        echo "Directory already exists: $(basename {{.RepoName}})" && exit 1;
+      if [ -d "$(basename \{{.RepoName}})" ]; then
+        echo "Directory already exists: $(basename \{{.RepoName}})" && exit 1;
       fi &&
-      gh repo clone "{{.RepoName}}" &&
-      cd "$(basename {{.RepoName}})" &&
-      if ! git checkout "{{.HeadRefName}}"; then
-        echo "Failed to checkout branch: {{.HeadRefName}}" && exit 1;
+      gh repo clone "\{{.RepoName}}" &&
+      cd "$(basename \{{.RepoName}})" &&
+      if ! git checkout "\{{.HeadRefName}}"; then
+        echo "Failed to checkout branch: \{{.HeadRefName}}" && exit 1;
       fi &&
       if ! command -v jj >/dev/null 2>&1; then
         echo "Command 'jj' not found. Skipping 'jj git init --colocate'." && exit 0;
